# Generated by Django 4.2.10 on 2024-03-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttypeproperty',
            name='object_type_property_name',
            field=models.CharField(max_length=50, verbose_name='ObjectTypeProperty'),
        ),
    ]
