# Generated by Django 4.2.10 on 2024-03-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_alter_objecttypeproperty_object_type_property_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objecttypeproperty',
            unique_together={('object_type', 'object_type_property_name')},
        ),
    ]
