# Generated by Django 4.2.10 on 2024-03-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_alter_objecttypeproperty_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclass',
            name='object_type_property',
            field=models.ForeignKey(default=1000001, on_delete=django.db.models.deletion.CASCADE, to='catalogapp.objecttypeproperty'),
            preserve_default=False,
        ),
    ]
