# Generated by Django 4.2.10 on 2024-03-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_alter_mainclass_object_type_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclass',
            name='date_time',
            field=models.CharField(db_column='date', max_length=50, null=True, verbose_name='Date'),
        ),
    ]
