# Generated by Django 4.2.10 on 2024-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_alter_mainclass_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainclass',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
